version: '2'

services:
  node:
    image: node:argon
    network_mode: 'bridge'
    working_dir: /usr/src/app
    volumes:
      - ".:/usr/src/app"
    ports:
      - "8080"
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=silent
      - CORS_ALLOW_ORIGINS=example1.com,example2.com
      - VIRTUAL_HOST=raido.dnt.privat
      - VIRTUAL_PORT=8080
    command: npm start

  postgres:
    image: turistforeningen/pgrouting-n50:latest
    network_mode: 'bridge'
